# -*- coding: utf-8 -*-
"""Data_Collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLi9ZGr0krsUpm91PVF8z0L4mp5ExGm7

## **Lexical Bridge Photo Mission - Data Collection**

### **Purpose**

The purpose of this notebook is to collect and prepare an image dataset for the Lexical Bridge photo mission feature. Images are downloaded from Open Images V7 using the FiftyOne dataset zoo, cropped using object bounding boxes, grouped into nine selected classes and three broader categories, then split into train, validation, and test sets. The final output is a zipped dataset file that can be reused for EDA and CNN model training.

### **Structure**
1. Install required libraries
2. Configure target classes, category mappings, and dataset paths
3. Download selected classes from Open Images V7
4. Extract bounding box crops from downloaded images
5. Clean temporary files
6. Split dataset into train, validation, and test sets
7. Visualize sample images
8. Export dataset as a ZIP file

## 1. Install Required Libraries
"""

!pip install -q fiftyone pillow tqdm

"""## 2. Dataset Configuration"""

import os
import random
import shutil
from pathlib import Path
from collections import defaultdict
from PIL import Image
from tqdm import tqdm

SEED = 42
random.seed(SEED)
# Require many samples for training own CNN model
TARGET_PER_CLASS = 1000
MAX_DOWNLOAD_SAMPLES = 25000
MIN_CROP_SIZE = 80  # Remove very small crops to improve training quality

# Map Open Images labels to the class names used in this project
FO_LABEL_MAP = {
    'Cat':       'cat',
    'Dog':       'dog',
    'Bird':      'bird',
    'Flower':    'flower',
    'Fruit':     'fruit',
    'Vegetable': 'vegetable',
    'Car':       'car',
    'Bicycle':   'bicycle',
    'Footwear':  'shoe',
}
FO_CLASSES = list(FO_LABEL_MAP.keys())

# Map detailed classes into broader game categories
CATEGORY_MAP = {
    'cat': 'animal',     'dog': 'animal',     'bird': 'animal',
    'flower': 'nature',  'fruit': 'nature',   'vegetable': 'nature',
    'car': 'daily_life', 'bicycle': 'daily_life', 'shoe': 'daily_life',
}

# Temporary working directories in the Colab environment
RAW_DIR     = Path('/content/open_images_raw')
CROP_DIR    = Path('/content/crops')
DATASET_DIR = Path('/content/dataset')

print(f'Classes: {list(CATEGORY_MAP.keys())}')
print(f'Target images per class: {TARGET_PER_CLASS}')
print(f'Maximum download samples: {MAX_DOWNLOAD_SAMPLES}')

"""## 3. Download Open Images V7 Dataset"""

import fiftyone as fo
import fiftyone.zoo as foz

# Remove existing Open Images datasets to avoid conflicts
for ds_name in fo.list_datasets():
    if 'open-images' in ds_name:
        fo.delete_dataset(ds_name)
        print(f'Deleted: {ds_name}')
print(f'Downloading Open Images V7 for: {FO_CLASSES}')
print(f'Maximum download samples: {MAX_DOWNLOAD_SAMPLES}')

# Download selected classes from Open Images V7 using the FiftyOne dataset zoo
fo_dataset = foz.load_zoo_dataset(
    'open-images-v7',
    split='train',
    label_types=['detections'],
    classes=FO_CLASSES,
    max_samples=MAX_DOWNLOAD_SAMPLES,
    shuffle=True,
    seed=SEED,
    only_matching=True
)

print(f'\nDownloaded samples: {len(fo_dataset)}')

"""## 4. Extract Bounding Box Crops"""

# Automatically detect the field that contains object detection labels
def get_detection_field(dataset):
    sample = dataset.first()
    for field_name in sample.field_names:
        value = sample.get_field(field_name)
        if isinstance(value, fo.core.labels.Detections):
            return field_name
    raise ValueError('No detection field found')

DETECTION_FIELD = get_detection_field(fo_dataset)
print(f'Detection field: {DETECTION_FIELD}')

# Reset the crop directory before saving new cropped images
if CROP_DIR.exists():
    shutil.rmtree(CROP_DIR)
for cls in FO_LABEL_MAP.values():
    (CROP_DIR / cls).mkdir(parents=True, exist_ok=True)

counts = defaultdict(int)
all_targets = set(FO_LABEL_MAP.values())

# Iterate through the downloaded images and extract object crops
for sample in tqdm(fo_dataset, desc='Cropping'):
    # Stop when all classes have reached the target number of images
    if all(counts[cls] >= TARGET_PER_CLASS for cls in all_targets):
        break
    try:
        image = Image.open(sample.filepath).convert('RGB')
    except:
        continue

    iw, ih = image.size
    detections = sample[DETECTION_FIELD].detections

    for det in detections:
        # Only keep labels selected for this project
        label = det.label
        if label not in FO_LABEL_MAP:
            continue
        cls = FO_LABEL_MAP[label]
        # Skip this class if the target count has already been reached
        if counts[cls] >= TARGET_PER_CLASS:
            continue

        # Convert normalized bounding box coordinates into pixel coordinates
        x, y, w, h = det.bounding_box
        left   = max(0,  int(x * iw))
        top    = max(0,  int(y * ih))
        right  = min(iw, int((x + w) * iw))
        bottom = min(ih, int((y + h) * ih))

        # Remove crops that are too small for reliable training
        if right - left < MIN_CROP_SIZE or bottom - top < MIN_CROP_SIZE:
            continue
        try:
            crop = image.crop((left, top, right, bottom))
            idx = counts[cls]
            crop.save(CROP_DIR / cls / f'{cls}_{idx:04d}.jpg', quality=95)
            counts[cls] += 1
        except:
            continue

print('\nCrop Summary')
for cls in sorted(all_targets):
    n = counts[cls]
    status = 'Complete' if n >= TARGET_PER_CLASS else 'Incomplete'
    print(f'  {status} {cls}: {n}/{TARGET_PER_CLASS}')
print(f'\nTotal cropped images: {sum(counts.values())}')

"""## 5. Clean Temporary Files"""

# Remove raw images downloaded by FiftyOne to free up disk space
if RAW_DIR.exists():
    shutil.rmtree(RAW_DIR)
    print(f'Deleted: {RAW_DIR}')

# Remove the default FiftyOne cache directory
FO_CACHE = Path(os.path.expanduser('~/.fiftyone'))
if FO_CACHE.exists():
    shutil.rmtree(FO_CACHE)
    print(f'Deleted: {FO_CACHE}')

# Check remaining disk usage in the Colab environment
!df -h /content

"""## 6. Split Dataset into Train, Validation, and Test Sets"""

# Reset the final dataset directory
if DATASET_DIR.exists():
    shutil.rmtree(DATASET_DIR)

# Create train, validation, and test folders for each class
for split in ['train', 'val', 'test']:
    for cls in CATEGORY_MAP:
        (DATASET_DIR / split / cls).mkdir(parents=True, exist_ok=True)

split_summary = {}

# Split cropped images into train / validation / test sets
for cls in CATEGORY_MAP:
    files = list((CROP_DIR / cls).glob('*.jpg'))
    random.shuffle(files)
    n = len(files)
    t1 = int(n * 0.70)
    t2 = int(n * 0.85)

    splits = {
        'train': files[:t1],
        'val':   files[t1:t2],
        'test':  files[t2:],
    }
    split_summary[cls] = {k: len(v) for k, v in splits.items()}

    # Copy each image into the corresponding split folder
    for split_name, file_list in splits.items():
        for f in file_list:
            shutil.copy(f, DATASET_DIR / split_name / cls / f.name)

print('Split Summary')
print(f'{"class":<12} {"train":>6} {"val":>6} {"test":>6} {"total":>6}')
print('-' * 41)
for cls, s in split_summary.items():
    total = s['train'] + s['val'] + s['test']
    print(f'{cls:<12} {s["train"]:>6} {s["val"]:>6} {s["test"]:>6} {total:>6}')

"""## 7. Visualize Sample Images"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(3, 3, figsize=(10, 10))
# Display one random training image from each class
for ax, cls in zip(axes.flatten(), CATEGORY_MAP.keys()):
    files = list((DATASET_DIR / 'train' / cls).glob('*.jpg'))
    if files:
        img = Image.open(random.choice(files)).convert('RGB')
        ax.imshow(img)

    # Show the class name and its broader category
    ax.set_title(f'{cls}\n({CATEGORY_MAP[cls]})', fontsize=10)
    ax.axis('off')
plt.tight_layout()
plt.show()

"""## 8. Export Dataset as ZIP File and download"""

from google.colab import files
zip_path = '/content/dyslexiread_dataset'
shutil.make_archive(zip_path, 'zip', str(DATASET_DIR))

size_mb = Path(f'{zip_path}.zip').stat().st_size / (1024 * 1024)
print(f'ZIP file created: {zip_path}.zip ({size_mb:.1f} MB)')
files.download('/content/dyslexiread_dataset.zip')